[package]
name = "rustcraft-server"
version = "0.1.0"
authors = ["Michał Majczak <michal.majczak92@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustcraft-engine = { path = "../engine", default-features = false, features = ["networking"]}